Rdpp 7427
Axway/api-builder-docs pull request #99
Opened 2022-08-18 13:42 UTC by wickedest

Thank you for your contribution to the API Builder documentation.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [ ] You have verified that all status checks have passed

_Put an x in the boxes that apply. This is simply a reminder of what we are going to look for before merging your change._

2022-08-19 16:06 UTC, alasdairhurst requested changes

2022-08-25 15:18 UTC, wickedest commented on content/en/docs/lifecycle/_index.md
> +Major versions of {{% variables/apibuilder_prod_name %}} are supported for a minimum of two years. Each major version is designated by an incremental number, e.g. v4, v5, etc. Every year around July,
As discussed, being specific is important for our customers, so changed to "around September".

2022-08-25 15:33 UTC, wickedest commented on content/en/docs/lifecycle/_index.md
> +| {{% variables/apibuilder_prod_name %}} version | Minimum | Minimum for CLI | Recommended             |
That's what this table is intended to be.  But y, it was too node specific. Expanded on the section a bit.

2022-08-25 15:40 UTC, wickedest commented on content/en/docs/lifecycle/_index.md
> +| ---------------------------------------------- | ------- | --------------- | ----------------------- |
Perhaps there should be a separate table for the CLI.  E.g. the v4 CLI went several breaking changes where the minimum of node changed, e.g. from 10 to 12.  I am not sure we need separate tables for all top-level products.  We'll see.  Anyway, this was a copy from the existing table, so I'll leave it as is for now for later consideration.

2022-08-26 10:23 UTC, closed without merging